
version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:stable
  working_directory: ~/project

commands:
  print_pipeline_id:
    description: "Print pipeline ID"
    parameters:
      id:
        type: string
        default: "ID should br here bro"
    steps:
      - run: 
          name: print pipeline id now
          command: echo <<parameters.id>>

jobs:
  say-hello:
    
    docker:
      - image: cimg/base:stable
    
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
